// Shared project ("agent") data — used by roster + detail pages.

export const PROJECTS = [
  {
    slug: 'nexus',
    id: 'AGT-01',
    name: 'NEXUS',
    role: 'CONTROLLER',
    hook: 'Real-time collaboration platform with sub-50ms sync.',
    desc: 'A multi-user workspace built on WebSockets and CRDTs. Handles document collab, presence, and offline-first sync. Deployed to 12k+ DAU.',
    palette: '#FF4655',
    year: '2024',
    status: 'LIVE',
    repo: 'https://github.com/meet/nexus',
    live: 'https://nexus.example.com',
    stack: [['Next.js', 92], ['Python', 88], ['Redis', 75], ['WebRTC', 70]],
    abilities: [
      ['Q', 'CRDT SYNC',    'Conflict-free state replication across N clients.'],
      ['E', 'PRESENCE',     'Avatars + cursors, throttled to 60fps.'],
      ['C', 'OFFLINE MODE', 'IndexedDB queue, syncs on reconnect.'],
      ['X', 'AUDIT TRAIL',  'Every keystroke timestamped + replayable.'],
    ],
    highlights: ['12k DAU', '99.95% uptime', '< 50ms p95 sync'],
  },
  {
    slug: 'oracle',
    id: 'AGT-02',
    name: 'ORACLE',
    role: 'SENTINEL',
    hook: 'AI-driven log anomaly detector for distributed systems.',
    desc: 'Streams logs through a fine-tuned classifier, flags anomalies in real-time, posts to Slack. Cut MTTR by 60% in production.',
    palette: '#7dd3fc',
    year: '2024',
    status: 'LIVE',
    repo: 'https://github.com/meet/oracle',
    live: null,
    stack: [['Python', 95], ['FastAPI', 90], ['ClickHouse', 80], ['LLMs', 85]],
    abilities: [
      ['Q', 'STREAM PARSE',  'Ingests 50k events/sec from Kafka.'],
      ['E', 'PATTERN SCAN',  'Fine-tuned model trained on 6mo of logs.'],
      ['C', 'SLACK ALERTS',  'Smart de-dupe so on-call doesn\u2019t scream.'],
      ['X', 'ROOT CAUSE',    'Auto-traces back to the offending commit.'],
    ],
    highlights: ['60% lower MTTR', '50k events/sec', '0 false-pos days'],
  },
  {
    slug: 'ghost',
    id: 'AGT-03',
    name: 'GHOST',
    role: 'DUELIST',
    hook: 'Privacy-first analytics SDK \u2014 cookieless, GDPR-clean.',
    desc: 'Tiny 3kb JS SDK pairing with an edge ingestion pipeline. Tracks events without third-party cookies. Powers 300+ sites.',
    palette: '#a78bfa',
    year: '2023',
    status: 'LIVE',
    repo: 'https://github.com/meet/ghost',
    live: 'https://ghost.example.com',
    stack: [['TypeScript', 90], ['Edge Functions', 85], ['Postgres', 78]],
    abilities: [
      ['Q', 'TINY SDK',    '3kb gzipped. Zero runtime deps.'],
      ['E', 'EDGE INGEST', 'Cloudflare workers, < 20ms p99.'],
      ['C', 'NO COOKIES',  'Server-side session hashing.'],
      ['X', 'EXPORT ANY',  'CSV, BigQuery, Postgres, S3 sinks.'],
    ],
    highlights: ['3kb gzipped', '300+ sites', 'GDPR \u2713'],
  },
  {
    slug: 'pyre',
    id: 'AGT-04',
    name: 'PYRE',
    role: 'INITIATOR',
    hook: 'Background job runner with visual DAG editor.',
    desc: 'Distributed task queue with a drag-and-drop pipeline builder. Used internally to orchestrate ETL across 40+ data sources.',
    palette: '#fbbf24',
    year: '2023',
    status: 'INTERNAL',
    repo: null,
    live: null,
    stack: [['React', 92], ['Python', 90], ['Celery', 80], ['Kafka', 70]],
    abilities: [
      ['Q', 'VISUAL DAG',  'Drag, drop, deploy. No YAML required.'],
      ['E', 'RETRY LOGIC', 'Backoff + jitter built-in.'],
      ['C', 'OBSERVABLE',  'Per-task traces, metrics, logs.'],
      ['X', 'SCALE WIDE',  'Burst to 200 workers in 30s.'],
    ],
    highlights: ['40+ sources', '200 workers', '8M tasks/day'],
  },
  {
    slug: 'beacon',
    id: 'AGT-05',
    name: 'BEACON',
    role: 'CONTROLLER',
    hook: 'Status page generator with public-API uptime monitoring.',
    desc: 'Spin up a branded status page in minutes. Hourly checks, incident comms, SLA reports. SaaS side-project, paying users.',
    palette: '#34d399',
    year: '2022',
    status: 'LIVE',
    repo: 'https://github.com/meet/beacon',
    live: 'https://beacon.example.com',
    stack: [['Next.js', 90], ['Postgres', 80], ['Cron', 75]],
    abilities: [
      ['Q', 'CHECK ARRAY',  'HTTP, TCP, DNS, SSL expiry.'],
      ['E', 'BRANDED PAGE', 'Custom domain + theme.'],
      ['C', 'INCIDENTS',    'Markdown updates, RSS, webhooks.'],
      ['X', 'SLA REPORT',   'PDFs auto-mailed monthly.'],
    ],
    highlights: ['paying users', 'multi-region', 'SLA reports'],
  },
  {
    slug: 'rune',
    id: 'AGT-06',
    name: 'RUNE',
    role: 'DUELIST',
    hook: 'AI agent that writes & ships PRs autonomously.',
    desc: 'Experimental coding agent that reads issues, plans, writes code, opens PRs. Built with Anthropic\u2019s SDK and a custom toolchain.',
    palette: '#FF4655',
    year: '2025',
    status: 'BETA',
    repo: null,
    live: null,
    stack: [['Python', 95], ['LLMs', 90], ['GitHub API', 85]],
    abilities: [
      ['Q', 'READ ISSUE',   'Parses Github issues + context.'],
      ['E', 'PLAN STEPS',   'Tree-of-thought before coding.'],
      ['C', 'OPEN PR',      'Clean diff, descriptive title, tests.'],
      ['X', 'SELF-REVIEW',  'Iterates until checks pass.'],
    ],
    highlights: ['merged in OSS', '~80% pass rate', 'tool-use heavy'],
  },
];

export function getProjectBySlug(slug) {
  return PROJECTS.find((p) => p.slug === slug) || null;
}
